version: "3"

services:

  runtime-setup:
    image: netty:centos-7-1.11
    build:
      args:
        centos_version : "7"
        java_version : "openjdk@1.11.0-1"

  test:
    image: netty:centos-7-1.11

  test-leak:
    image: netty:centos-7-1.11

  test-boringssl-static:
    image: netty:centos-7-1.11

  shell:
    image: netty:centos-7-1.11
